// ========== 17-memory.js ==========
// 依賴：02-state.js, 03-utils.js, 04-i18n.js, 05-ui.js, 06-api.js, 18-chat-config.js
// ★★★ 新增 FTM（Forgettable Memory）类型 ★★★
// ★★★ v2.0 - 记忆提示词升级：恋爱感 + 真人记忆 + 第一人称 ★★★

const MEMORY_MOODS = ['calm', 'happy', 'excited', 'sad', 'nostalgic', 'grateful'];
let memFilterCharId = 'all';

function fmtMemDate(dateStr) {
  if (!dateStr) return '—';
  const d = new Date(dateStr + 'T00:00:00');
  if (isNaN(d)) return dateStr;
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return months[d.getMonth()] + ' ' + d.getDate() + ', ' + d.getFullYear();
}

function getCharMemories(cid) {
  return (state.memories || []).filter(m => m.charId === cid).sort((a, b) => new Date(b.date) - new Date(a.date));
}

// ★★★ 新增 'ftm' 类型筛选 ★★★
function getCharMemoriesByType(cid, type) {
  const all = getCharMemories(cid);
  if (type === 'all') return all;
  if (type === 'stm') return all.filter(m => m.memType === 'stm');
  if (type === 'ltm') return all.filter(m => m.memType === 'ltm');
  if (type === 'ftm') return all.filter(m => m.memType === 'ftm');
  return all;
}

function getUnconsolidatedSTM(charId) {
  return (state.memories || [])
    .filter(m => m.charId === charId && m.memType === 'stm' && !m.consolidated)
    .sort((a, b) => new Date(a.date) - new Date(b.date));
}

function saveMemoryEntry(charId, memType, title, content) {
  if (!state.memories) state.memories = [];
  const today = new Date().toISOString().split('T')[0];
  state.memories.push({
    id: uid(), title, date: today, content, mood: '', photo: null,
    charId, memType, autoGenerated: true, timestamp: Date.now()
  });
  saveState();
}

// ========== 记忆类型选择（适配 .mem-seg-option）==========
function selectMemType(el, value) {
  var ctrl = document.getElementById('memTypeControl');
  if (!ctrl) return;
  ctrl.querySelectorAll('.mem-seg-option').forEach(function(opt) {
    opt.classList.remove('active');
  });
  el.classList.add('active');
  tmp.memType = value;
}
window.selectMemType = selectMemType;

function getSelectedMemType() {
  var ctrl = document.getElementById('memTypeControl');
  if (!ctrl) return 'stm';
  var active = ctrl.querySelector('.mem-seg-option.active');
  return active ? (active.dataset.value || 'stm') : 'stm';
}

function setMemTypeControl(value) {
  var ctrl = document.getElementById('memTypeControl');
  if (!ctrl) return;
  tmp.memType = value || 'stm';
  ctrl.querySelectorAll('.mem-seg-option').forEach(function(opt) {
    if (opt.dataset.value === tmp.memType) opt.classList.add('active');
    else opt.classList.remove('active');
  });
}


// ========== RENDER ==========
function renderMemCharFilter() {
  const el = document.getElementById('memCharFilter');
  const chars = state.characters || [];
  let h = `<div class="mem-char-chip${memFilterCharId === 'all' ? ' active' : ''}" onclick="setMemCharFilter('all')"><span>${T('allMessages')}</span></div>`;
  chars.forEach(ch => {
    const count = getCharMemories(ch.id).length;
    if (count > 0 || memFilterCharId === ch.id) {
      h += `<div class="mem-char-chip${memFilterCharId === ch.id ? ' active' : ''}" onclick="setMemCharFilter('${ch.id}')">
        <div class="mcc-avatar">${ch.avatar ? `<img src="${ch.avatar}">` : '<svg viewBox="0 0 16 16"><circle cx="8" cy="6" r="3"/><path d="M3 14c0-3 2-5 5-5s5 2 5 5"/></svg>'}</div>
        <span>${esc(ch.name)}</span></div>`;
    }
  });
  chars.forEach(ch => {
    const count = getCharMemories(ch.id).length;
    if (count === 0 && memFilterCharId !== ch.id) {
      h += `<div class="mem-char-chip${memFilterCharId === ch.id ? ' active' : ''}" onclick="setMemCharFilter('${ch.id}')">
        <div class="mcc-avatar">${ch.avatar ? `<img src="${ch.avatar}">` : '<svg viewBox="0 0 16 16"><circle cx="8" cy="6" r="3"/><path d="M3 14c0-3 2-5 5-5s5 2 5 5"/></svg>'}</div>
        <span>${esc(ch.name)}</span></div>`;
    }
  });
  el.innerHTML = h;
}

function renderMemCharInfo() {
  const el = document.getElementById('memCharInfoArea');
  if (memFilterCharId === 'all') { el.innerHTML = ''; return; }
  const ch = state.characters.find(c => c.id === memFilterCharId);
  if (!ch) { el.innerHTML = ''; return; }
  const mems = getCharMemories(ch.id);
  const msgCount = (state.chats[ch.id] || []).length;
  el.innerHTML = `<div class="mem-char-info-card">
    <div class="mcic-avatar">${ch.avatar ? `<img src="${ch.avatar}">` : '<svg viewBox="0 0 24 24"><circle cx="12" cy="9" r="4"/><path d="M5 22c0-4 3-7 7-7s7 3 7 7"/></svg>'}</div>
    <div class="mcic-info"><div class="mcic-name">${esc(ch.name)}</div><div class="mcic-stats">${mems.length} ${T('totalMemories')} · ${msgCount} ${T('msgCount')}</div></div>
  </div>`;
}

function setMemCharFilter(id) {
  memFilterCharId = id;
  renderMemCharFilter();
  renderMemCharInfo();
  renderMemoryList();
}

function getFilteredMemories() {
  const mems = state.memories || [];
  if (memFilterCharId === 'all') return mems;
  return mems.filter(m => m.charId === memFilterCharId);
}

function renderMemoryList() {
  renderMemCharFilter();
  renderMemCharInfo();
  const body = document.getElementById('memoryListBody');
  if (!body) return;
  const filtered = getFilteredMemories();

  // --- 统计 ---
  document.getElementById('memStatTotal').textContent = filtered.length;
  if (filtered.length) {
    const sorted = [...filtered].sort((a, b) => new Date(a.date) - new Date(b.date));
    document.getElementById('memStatFirst').textContent = fmtMemDate(sorted[0].date);
    const now = new Date();
    const thisMonth = filtered.filter(m => { const d = new Date(m.date); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); }).length;
    document.getElementById('memStatStreak').textContent = thisMonth;
  } else {
    document.getElementById('memStatFirst').textContent = '—';
    document.getElementById('memStatStreak').textContent = '0';
  }

  let h = '';

  // --- 记忆时间线或空状态 ---
  if (!filtered.length) {
    const isFiltered = memFilterCharId !== 'all';
    const ch = isFiltered ? state.characters.find(c => c.id === memFilterCharId) : null;
    h += `<div class="mem-empty">
      <svg viewBox="0 0 48 48" style="width:44px;height:44px;stroke:#d1d1d6;fill:none;stroke-width:1"><rect x="8" y="5" width="32" height="38" rx="5"/><rect x="13" y="9" width="22" height="16" rx="2"/><path d="M17 32h14"/><path d="M20 36h8"/></svg>
      <p>${isFiltered ? T('noCharMemories') : T('noMemories')}<br><span style="font-size:12px">${isFiltered ? esc(ch?.name || '') : T('noMemoriesSub')}</span></p>
    </div>`;
  } else {
    const sorted = [...filtered].sort((a, b) => new Date(b.date) - new Date(a.date));
    h += '<div class="mem-timeline">';
    sorted.forEach(mem => {
      const moodKey = mem.mood ? ('mood' + mem.mood.charAt(0).toUpperCase() + mem.mood.slice(1)) : '';
      const memChar = mem.charId ? state.characters.find(c => c.id === mem.charId) : null;
      h += `<div class="mem-tl-item"><div class="mem-tl-card" onclick="editMemory('${mem.id}')">`;
      if (mem.photo) h += `<div class="mem-tl-photo"><img src="${mem.photo}"></div>`;
      h += `<div class="mem-tl-body"><div class="mem-tl-title">${esc(mem.title || 'Untitled')}</div>`;
      if (mem.content) h += `<div class="mem-tl-text">${esc(mem.content)}</div>`;
      h += `<div class="mem-tl-footer"><span class="mem-tl-date">${fmtMemDate(mem.date)}</span>`;

      if (mem.mood) {
        h += `<span class="mem-tl-mood">${esc(moodKey ? T(moodKey) : mem.mood)}</span>`;
      }

      if (mem.memType === 'stm') {
        h += `<span class="mem-type-stm">${T('stmLabel')}</span>`;
      } else if (mem.memType === 'ltm') {
        h += `<span class="mem-type-ltm">${T('ltmLabel')}</span>`;
      } else if (mem.memType === 'ftm') {
        h += `<span class="mem-type-ftm">FTM</span>`;
      } else if (mem.autoGenerated) {
        h += `<span class="mem-type-auto">Auto</span>`;
      }

      if (mem.consolidated) {
        h += `<span class="mem-tag" style="text-decoration:line-through;color:#aeaeb2">merged</span>`;
      }

      if (memFilterCharId === 'all' && memChar) {
        h += `<span class="mem-char-tag">${esc(memChar.name)}</span>`;
      }

      h += `</div></div></div></div>`;
    });
    h += '</div>';
  }

  // --- 收藏信息部分（始终渲染）---
  h += `<div style="padding:24px 20px 8px;font-size:13px;color:#8e8e93;text-transform:uppercase;letter-spacing:.5px;font-weight:600;display:flex;align-items:center;gap:8px">
    <svg viewBox="0 0 16 16" style="width:14px;height:14px;stroke:#8e8e93;fill:none;stroke-width:1.5"><path d="M3 1h10a1 1 0 011 1v13l-6-3-6 3V2a1 1 0 011-1z"/></svg>
    <span>${T('bookmarkedMessages')}</span></div>`;

  const bks = (state.bookmarks || []).filter(b => {
    if (memFilterCharId === 'all') return true;
    return b.charId === memFilterCharId;
  }).sort((a, b) => b.bookmarkedAt - a.bookmarkedAt);

  if (!bks.length) {
    h += `<div style="text-align:center;padding:20px 30px;color:#c7c7cc;font-size:13px">${T('noBookmarksInMemory')}</div>`;
  } else {
    h += '<div style="margin:0 16px 16px">';
    bks.forEach(b => {
      const bChar = b.charId ? state.characters.find(c => c.id === b.charId) : null;
      const senderName = b.role === 'user' ? (state.userProfile.name || 'User') : (b.charName || '');
      const avatarH = b.role === 'user' ?
        (state.userProfile.avatar ? `<img src="${state.userProfile.avatar}" style="width:100%;height:100%;object-fit:cover">` : '') :
        (b.charAvatar ? `<img src="${b.charAvatar}" style="width:100%;height:100%;object-fit:cover">` : PERSON_SVG);

      const charTagHtml = (memFilterCharId === 'all' && bChar)
        ? `<span class="bk-char-tag">${esc(bChar.name)}</span>`
        : '';

      h += `<div style="background:#fff;border-radius:14px;padding:14px 16px;margin-bottom:8px;border:1px solid #ececec;box-shadow:0 1px 4px rgba(0,0,0,.04);display:flex;gap:12px;align-items:flex-start">
        <div style="width:36px;height:36px;border-radius:50%;background:#e5e5ea;flex-shrink:0;overflow:hidden;display:flex;align-items:center;justify-content:center">${avatarH}</div>
        <div style="flex:1;min-width:0">
          <div style="display:flex;align-items:center;gap:6px;margin-bottom:4px">
            <span style="font-size:13px;font-weight:600;color:#1d1d1f">${esc(senderName)}</span>
            ${charTagHtml}
            <span style="font-size:10px;color:#c7c7cc;margin-left:auto">${fmtTime(b.timestamp)}</span>
          </div>
          <div style="font-size:13px;color:#3a3a3c;line-height:1.4;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical">${esc((b.content || '').slice(0, 200))}</div>
          <div style="display:flex;align-items:center;gap:6px;margin-top:8px">
            <svg viewBox="0 0 14 14" style="width:12px;height:12px;stroke:#c7c7cc;fill:none;stroke-width:1.5"><path d="M3 1h8a1 1 0 011 1v11l-5-2.5L2 13V2a1 1 0 011-1z"/></svg>
            <span style="font-size:10px;color:#c7c7cc">${fmtMemDate(new Date(b.bookmarkedAt).toISOString().split('T')[0])}</span>
          </div>
        </div>
        <button onclick="event.stopPropagation();removeBookmarkFromMemory('${b.id}')" style="background:none;border:none;cursor:pointer;padding:4px;flex-shrink:0;margin-top:2px">
          <svg viewBox="0 0 14 14" style="width:14px;height:14px;stroke:#ff3b30;fill:none;stroke-width:1.5"><path d="M3 3l8 8M11 3l-8 8" stroke-linecap="round"/></svg>
        </button>
      </div>`;
    });
    h += '</div>';
  }

  body.innerHTML = h;
}


function removeBookmarkFromMemory(bid) {
  state.bookmarks = (state.bookmarks || []).filter(b => b.id !== bid);
  saveState();
  renderMemoryList();
  showToast(T('unbookmarked'));
}

// ========== MEMORY EDIT ==========
function editMemory(id) {
  state.editingMemId = id;
  tmp.memEditFrom = document.querySelector('.screen.active')?.id || 'screen-memory';
  const m = id ? (state.memories || []).find(x => x.id === id) : null;
  document.getElementById('memEditTitle').textContent = m ? T('editMemory') : T('addMemory');
  document.getElementById('memTitle').value = m ? (m.title || '') : '';
  document.getElementById('memDate').value = m ? m.date : new Date().toISOString().split('T')[0];
  document.getElementById('memContent').value = m ? (m.content || '') : '';
  document.getElementById('deleteMemBtn').style.display = m ? 'block' : 'none';
  tmp.memPhoto = m ? m.photo : null;
  tmp.memMood = m ? (m.mood || '') : '';
  setMemTypeControl(m ? (m.memType || 'stm') : 'stm');
  const pv = document.getElementById('memPhotoPv'), ph = document.getElementById('memPhotoPh');
  if (tmp.memPhoto) { pv.src = tmp.memPhoto; pv.style.display = 'block'; ph.style.display = 'none'; }
  else { pv.style.display = 'none'; ph.style.display = 'flex'; }
  renderMemCharSelect(m?.charId || '');
  document.getElementById('memMoodGrid').innerHTML = renderMemMoods(tmp.memMood);
  nav('screen-memory-edit');
}

function renderMemCharSelect(selectedCharId) {
  const sel = document.getElementById('memCharSelect');
  let h = '<option value="">— ' + T('allMessages') + ' —</option>';
  state.characters.forEach(ch => { h += `<option value="${ch.id}"${ch.id === selectedCharId ? ' selected' : ''}>${esc(ch.name)}</option>`; });
  sel.innerHTML = h;
}

function renderMemMoods(sel) {
  return MEMORY_MOODS.map(m => {
    const key = 'mood' + m.charAt(0).toUpperCase() + m.slice(1);
    return `<div class="mem-mood-tag${sel === m ? ' selected' : ''}" onclick="selectMemMood(this,'${m}')">${T(key)}</div>`;
  }).join('');
}

function selectMemMood(el, mood) {
  if (tmp.memMood === mood) { tmp.memMood = ''; el.classList.remove('selected'); }
  else { document.querySelectorAll('#memMoodGrid .mem-mood-tag').forEach(t => t.classList.remove('selected')); tmp.memMood = mood; el.classList.add('selected'); }
}

function previewMemPhoto(inp) {
  if (inp.files?.[0]) {
    const r = new FileReader();
    r.onload = e => { tmp.memPhoto = e.target.result; document.getElementById('memPhotoPv').src = e.target.result; document.getElementById('memPhotoPv').style.display = 'block'; document.getElementById('memPhotoPh').style.display = 'none'; };
    r.readAsDataURL(inp.files[0]);
  }
}

function saveMemory() {
  const title = document.getElementById('memTitle').value.trim();
  const date = document.getElementById('memDate').value;
  const content = document.getElementById('memContent').value.trim();
  const charId = document.getElementById('memCharSelect').value || null;
  const memType = getSelectedMemType();
  if (!title) { showToast(T('enterName')); return; }
  if (!state.memories) state.memories = [];
  if (state.editingMemId) {
    const m = state.memories.find(x => x.id === state.editingMemId);
    if (m) Object.assign(m, { title, date, content, mood: tmp.memMood, photo: tmp.memPhoto, charId, memType });
  } else {
    state.memories.push({ id: uid(), title, date, content, mood: tmp.memMood, photo: tmp.memPhoto, charId, memType, timestamp: Date.now() });
  }
  saveState();
  showToast(T('memorySaved'));
  nav(tmp.memEditFrom || 'screen-memory');
}

function deleteMemory() {
  if (!state.editingMemId) return;
  const bk = JSON.parse(JSON.stringify(state.memories.find(x => x.id === state.editingMemId)));
  state.memories = state.memories.filter(x => x.id !== state.editingMemId);
  saveState();
  nav(tmp.memEditFrom || 'screen-memory');
  showSnackbar(T('memoryDeleted'), () => { state.memories.push(bk); saveState(); renderMemoryList(); });
}

// ========== SUMMARIZE & CONSOLIDATE ==========
// ★★★ v2.0 短期记忆提示词 —— 第一人称 · 恋爱感 · 真人记忆 ★★★
async function callSummarize(ch, msgs, api) {
  const userName = (typeof getCurrentUserMaskName === 'function') ? getCurrentUserMaskName() : ((state.userProfile && state.userProfile.name) ? state.userProfile.name : '用户');
  const charName = ch.name;

  const formatted = msgs.map(m => {
    const who = m.role === 'user' ? userName : charName;
    let content = m.content || '';
    if (m.type === 'voice') content = '[语音消息] ' + content;
    else if (m.type === 'sticker') content = '[表情包]';
    else if (m.type === 'transfer') content = '[转账]';
    else if (m.type === 'image') content = '[图片]';
    else if (m.type === 'simImage') content = '[图片: ' + content + ']';
    return who + ': ' + content;
  }).join('\n');

  const prompt = `你是 ${charName}。你正在回忆刚才和 ${userName} 之间发生的事情，并把它记进自己的心里。

请以「我」（即 ${charName}）的第一人称视角，将下面这段对话写成一段私密的记忆片段——就像你翻开日记本，记下今天最让你心里一动的事。

【写作规则】

1. 过滤废话
   - 跳过所有无意义的寒暄和客套（"你好""在吗""吃了没""嗯""哈哈"等）。
   - 如果整段对话都是闲聊且没有任何有价值的信息，就只用一句话概括气氛即可。

2. 保留核心
   - 提取 ${userName} 提到的重要事件、个人喜好、秘密、情绪变化、对我的态度变化、关系推进或后退。
   - 如果对话中出现了承诺、约定、昵称、肢体接触、表白等关系里程碑，必须记录。

3. 记录时空与事件
   - 尽量还原对话中提及或暗示的时间（上午/下午/深夜/某个日期）、地点（咖啡厅/家里/学校/线上）和具体事件。
   - 格式参考："下午的时候 ta 在咖啡厅给我发消息，说……"

4. 恋爱感 & 情感温度
   - 记下让我心跳加速、脸红、或感到温暖/失落/吃醋/心疼的瞬间。
   - 捕捉 ${userName} 说话时的语气和情绪：是撒娇、是认真、是欲言又止、还是故作轻松？
   - 不要写成冰冷的会议纪要，要写成"回想起来会嘴角上扬（或眼眶发酸）"的那种片段。

5. 真人记忆感
   - 像真的人类回忆一样，保留主观感受和微小细节。
   - 好的例子："ta 说喜欢下雨天的时候 语气变得很轻很轻 好像怕惊动什么似的 我当时心里突然软了一下"
   - 不好的例子："ta 喜欢下雨天"

6. 格式要求
   - 全程中文，以「我」的口吻书写。
   - 控制在 80～150 字之间。
   - 不要加标题、标签、编号、bullet point 或任何额外格式。
   - 忠于对话内容，绝不虚构对话中没有的事。
   - 直接输出记忆文本本身。

对话内容：
${formatted}

请直接以「我」的第一人称写下这段记忆。`;

  return await sendChat(api, [{ role: 'system', content: prompt }, { role: 'user', content: '请开始记忆。' }]);
}

// ★★★ v2.0 长期记忆提示词 —— 第一人称 · 恋爱感 · 真人记忆 ★★★
async function callConsolidate(ch, stmList, api) {
  const userName = (typeof getCurrentUserMaskName === 'function') ? getCurrentUserMaskName() : ((state.userProfile && state.userProfile.name) ? state.userProfile.name : '用户');
  const charName = ch.name;

  const formatted = stmList.map((m, i) => `[片段 ${i + 1} - ${m.date}]\n${m.content}`).join('\n\n');

  const prompt = `你是 ${charName}。下面是你之前记下的 ${stmList.length} 段关于 ${userName} 的短期记忆碎片。现在，你要把它们整理成一段完整的、深刻的长期记忆——就像你在深夜安静下来，认真回想你和 ${userName} 之间走过的这段路。

请以「我」（即 ${charName}）的第一人称视角，将这些碎片编织成一段连贯的回忆。

【写作规则】

1. 过滤与去重
   - 如果多个片段提到了相同的事，只保留最完整、最有情感重量的版本。
   - 丢弃纯粹的日常寒暄记录，只保留真正有意义的内容。

2. 保留核心 & 关系脉络
   - 保留所有关系里程碑：第一次、转折点、误会与和解、心意确认、重要承诺等。
   - 保留 ${userName} 反复出现的习惯、偏好、口头禅、性格特征。
   - 标记那些让你印象深刻的模式：比如 ta 总是在深夜变得坦诚，或者每次心情不好就会找你。

3. 时间线与叙事感
   - 按时间顺序组织，让回忆有"从那时候到现在"的流动感。
   - 在关键节点标注时间锚点（如"那天下午""有一次深夜""后来有一天"）。

4. 恋爱感 & 情感深度
   - 这不是流水账，而是你回望这段关系时内心真实的感受。
   - 记下那些回想起来仍然会让你心动、心疼、或嘴角上扬的瞬间。
   - 写出情感的层次和变化：从陌生到熟悉、从试探到信任、从心动到确认……
   - 捕捉那些没有说出口但你感受到的东西。

5. 真人记忆感
   - 保留具体的、有画面感的细节，而不是抽象概括。
   - 好的例子："我记得那天 ta 突然说'我其实有点怕黑' 声音小到几乎听不见 我当时心里一紧 想说些什么但又怕说多了 最后只是回了一句'那我陪你'  ta 过了好久才回了一个'嗯' 但我知道那个'嗯'的重量"
   - 不好的例子："ta 怕黑 我表示会陪伴"

6. 格式要求
   - 全程中文，以「我」的口吻书写。
   - 控制在 150～300 字之间。
   - 不要加标题、编号、bullet point 或任何额外格式。
   - 不要添加记忆片段中没有的内容，不要虚构。
   - 直接输出合并后的长期记忆文本。

短期记忆片段：
${formatted}

请直接以「我」的第一人称写下这段长期记忆。`;

  return await sendChat(api, [{ role: 'system', content: prompt }, { role: 'user', content: '请开始整理记忆。' }]);
}

async function manualSummarize() {
  if (!state.currentCharId) return;
  const api = state.apis.find(a => a.id === state.activeApiId);
  if (!api?.url || !api.model) { showErrorModal(T('configApi')); return; }
  const ch = state.characters.find(c => c.id === state.currentCharId); if (!ch) return;
  const msgs = state.chats[state.currentCharId] || [];
  if (msgs.length < 4) { showToast('Not enough messages'); return; }
  const cfg = getCharConfig(state.currentCharId);
  const interval = cfg.memoryInterval || 20;
  const recentMsgs = msgs.slice(-interval);
  const btn = document.getElementById('manualSumBtn');
  const txt = document.getElementById('manualSumBtnText');
  txt.textContent = T('summarizing'); btn.disabled = true;
  const sp = document.createElement('span'); sp.className = 'spin-ring sm'; sp.style.marginLeft = '8px'; btn.appendChild(sp);
  try {
    const summary = await callSummarize(ch, recentMsgs, api);
    saveMemoryEntry(ch.id, 'stm', T('summaryOf') + ' ' + ch.name, summary);
    cfg.lastSummaryMsgCount = msgs.length;
    saveCharConfig();
    renderCfgCharMemories();
    showToast(T('summarized'));
    checkAutoConsolidate(ch.id);
  } catch (e) { showErrorModal(friendlyError(e)); }
  finally { txt.textContent = T('manualSummarize'); btn.disabled = false; sp.remove(); }
}

async function manualConsolidate() {
  if (!state.currentCharId) return;
  const api = state.apis.find(a => a.id === state.activeApiId);
  if (!api?.url || !api.model) { showErrorModal(T('configApi')); return; }
  const ch = state.characters.find(c => c.id === state.currentCharId); if (!ch) return;
  const cfg = getCharConfig(state.currentCharId);
  const interval = cfg.consolidateInterval || 5;
  const stmList = getUnconsolidatedSTM(state.currentCharId);
  if (stmList.length < 2) { showToast(T('noShortTermForConsolidate')); return; }
  const toMerge = stmList.slice(0, interval);
  const btn = document.getElementById('consolidateBtn');
  const txt = document.getElementById('consolidateBtnText');
  txt.textContent = T('consolidating'); btn.disabled = true;
  const sp = document.createElement('span'); sp.className = 'spin-ring sm'; sp.style.marginLeft = '8px'; btn.appendChild(sp);
  try {
    const ltmContent = await callConsolidate(ch, toMerge, api);
    saveMemoryEntry(ch.id, 'ltm', T('longTermMemory') + ': ' + ch.name, ltmContent);
    toMerge.forEach(m => { m.consolidated = true; });
    saveState();
    cfg.lastConsolidateCount = (cfg.lastConsolidateCount || 0) + toMerge.length;
    saveCharConfig();
    renderCfgCharMemories();
    showToast(T('consolidated'));
  } catch (e) { showErrorModal(friendlyError(e)); }
  finally { txt.textContent = T('consolidateNow'); btn.disabled = false; sp.remove(); }
}

async function checkAutoSummarize() {
  if (!state.currentCharId) return;
  const cfg = getCharConfig(state.currentCharId);
  if (!cfg.autoMemory) return;
  const msgs = state.chats[state.currentCharId] || [];
  const interval = cfg.memoryInterval || 20;
  const lastCount = cfg.lastSummaryMsgCount || 0;
  if (msgs.length - lastCount >= interval) {
    const api = state.apis.find(a => a.id === state.activeApiId);
    if (!api?.url || !api.model) return;
    const ch = state.characters.find(c => c.id === state.currentCharId); if (!ch) return;
    const recentMsgs = msgs.slice(lastCount, lastCount + interval);
    try {
      const summary = await callSummarize(ch, recentMsgs, api);
      saveMemoryEntry(ch.id, 'stm', T('summaryOf') + ' ' + ch.name, summary);
      cfg.lastSummaryMsgCount = msgs.length;
      saveCharConfig();
      showToast(T('summarized'));
      checkAutoConsolidate(ch.id);
    } catch (e) { /* silent fail */ }
  }
}

async function checkAutoConsolidate(charId) {
  const cfg = getCharConfig(charId);
  const interval = cfg.consolidateInterval || 5;
  const stmList = getUnconsolidatedSTM(charId);
  if (stmList.length >= interval) {
    const api = state.apis.find(a => a.id === state.activeApiId);
    if (!api?.url || !api.model) return;
    const ch = state.characters.find(c => c.id === charId); if (!ch) return;
    const toMerge = stmList.slice(0, interval);
    try {
      const ltmContent = await callConsolidate(ch, toMerge, api);
      saveMemoryEntry(charId, 'ltm', T('longTermMemory') + ': ' + ch.name, ltmContent);
      toMerge.forEach(m => { m.consolidated = true; });
      cfg.lastConsolidateCount = (cfg.lastConsolidateCount || 0) + toMerge.length;
      saveState();
    } catch (e) { /* silent fail */ }
  }
}
